// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module keygen_poly_sub_scaled_ntt_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        vla18_address0,
        vla18_ce0,
        vla18_we0,
        vla18_d0,
        vla18_q0,
        vla18_address1,
        vla18_ce1,
        vla18_we1,
        vla18_d1,
        vla18_q1,
        F,
        Flen,
        Fstride,
        f_r,
        flen_r,
        fstride_r,
        k,
        sch,
        scl,
        logn,
        tmp,
        PRIMES_p_address0,
        PRIMES_p_ce0,
        PRIMES_p_q0,
        PRIMES_g_address0,
        PRIMES_g_ce0,
        PRIMES_g_q0
);

parameter    ap_ST_fsm_state1 = 44'd1;
parameter    ap_ST_fsm_state2 = 44'd2;
parameter    ap_ST_fsm_state3 = 44'd4;
parameter    ap_ST_fsm_state4 = 44'd8;
parameter    ap_ST_fsm_state5 = 44'd16;
parameter    ap_ST_fsm_state6 = 44'd32;
parameter    ap_ST_fsm_state7 = 44'd64;
parameter    ap_ST_fsm_state8 = 44'd128;
parameter    ap_ST_fsm_state9 = 44'd256;
parameter    ap_ST_fsm_state10 = 44'd512;
parameter    ap_ST_fsm_state11 = 44'd1024;
parameter    ap_ST_fsm_state12 = 44'd2048;
parameter    ap_ST_fsm_state13 = 44'd4096;
parameter    ap_ST_fsm_state14 = 44'd8192;
parameter    ap_ST_fsm_state15 = 44'd16384;
parameter    ap_ST_fsm_state16 = 44'd32768;
parameter    ap_ST_fsm_state17 = 44'd65536;
parameter    ap_ST_fsm_state18 = 44'd131072;
parameter    ap_ST_fsm_state19 = 44'd262144;
parameter    ap_ST_fsm_state20 = 44'd524288;
parameter    ap_ST_fsm_state21 = 44'd1048576;
parameter    ap_ST_fsm_state22 = 44'd2097152;
parameter    ap_ST_fsm_state23 = 44'd4194304;
parameter    ap_ST_fsm_state24 = 44'd8388608;
parameter    ap_ST_fsm_state25 = 44'd16777216;
parameter    ap_ST_fsm_state26 = 44'd33554432;
parameter    ap_ST_fsm_state27 = 44'd67108864;
parameter    ap_ST_fsm_state28 = 44'd134217728;
parameter    ap_ST_fsm_state29 = 44'd268435456;
parameter    ap_ST_fsm_state30 = 44'd536870912;
parameter    ap_ST_fsm_state31 = 44'd1073741824;
parameter    ap_ST_fsm_state32 = 44'd2147483648;
parameter    ap_ST_fsm_state33 = 44'd4294967296;
parameter    ap_ST_fsm_state34 = 44'd8589934592;
parameter    ap_ST_fsm_state35 = 44'd17179869184;
parameter    ap_ST_fsm_state36 = 44'd34359738368;
parameter    ap_ST_fsm_state37 = 44'd68719476736;
parameter    ap_ST_fsm_state38 = 44'd137438953472;
parameter    ap_ST_fsm_state39 = 44'd274877906944;
parameter    ap_ST_fsm_state40 = 44'd549755813888;
parameter    ap_ST_fsm_state41 = 44'd1099511627776;
parameter    ap_ST_fsm_state42 = 44'd2199023255552;
parameter    ap_ST_fsm_state43 = 44'd4398046511104;
parameter    ap_ST_fsm_state44 = 44'd8796093022208;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] vla18_address0;
output   vla18_ce0;
output  [3:0] vla18_we0;
output  [31:0] vla18_d0;
input  [31:0] vla18_q0;
output  [12:0] vla18_address1;
output   vla18_ce1;
output  [3:0] vla18_we1;
output  [31:0] vla18_d1;
input  [31:0] vla18_q1;
input  [14:0] F;
input  [63:0] Flen;
input  [8:0] Fstride;
input  [14:0] f_r;
input  [7:0] flen_r;
input  [7:0] fstride_r;
input  [14:0] k;
input  [27:0] sch;
input  [5:0] scl;
input  [3:0] logn;
input  [14:0] tmp;
output  [9:0] PRIMES_p_address0;
output   PRIMES_p_ce0;
input  [24:0] PRIMES_p_q0;
output  [9:0] PRIMES_g_address0;
output   PRIMES_g_ce0;
input  [30:0] PRIMES_g_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[12:0] vla18_address0;
reg vla18_ce0;
reg[3:0] vla18_we0;
reg[31:0] vla18_d0;
reg[12:0] vla18_address1;
reg vla18_ce1;
reg[3:0] vla18_we1;
reg[31:0] vla18_d1;
reg[9:0] PRIMES_p_address0;
reg PRIMES_p_ce0;
reg PRIMES_g_ce0;

(* fsm_encoding = "none" *) reg   [43:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] REV10_address0;
reg    REV10_ce0;
wire   [9:0] REV10_q0;
wire   [31:0] grp_modp_montymul_fu_800_ap_return;
reg   [31:0] reg_549;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state36;
reg   [63:0] reg_700;
wire    ap_CS_fsm_state13;
wire   [0:0] tmp_173_fu_1672_p3;
reg   [31:0] reg_779;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln779_fu_1624_p2;
wire   [0:0] icmp_ln781_fu_1640_p2;
reg   [63:0] reg_791;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln954_fu_1651_p2;
reg   [31:0] x1_3_reg_1021;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln962_fu_1724_p2;
reg   [31:0] x2_2_reg_1054;
wire    ap_CS_fsm_state17;
wire  signed [31:0] scl_cast_fu_1190_p1;
reg  signed [31:0] scl_cast_reg_3075;
wire   [8:0] flen_cast14_fu_1194_p1;
reg   [8:0] flen_cast14_reg_3080;
wire   [17:0] fstride_cast_fu_1198_p1;
reg   [17:0] fstride_cast_reg_3085;
wire   [31:0] logn_cast7_fu_1202_p1;
reg   [31:0] logn_cast7_reg_3090;
wire   [18:0] Fstride_cast_fu_1206_p1;
reg   [18:0] Fstride_cast_reg_3095;
wire   [10:0] m_4_fu_1226_p2;
reg   [10:0] m_4_reg_3100;
wire   [63:0] zext_ln1329_fu_1232_p1;
reg   [63:0] zext_ln1329_reg_3112;
wire   [11:0] zext_ln1329_1_fu_1236_p1;
reg   [11:0] zext_ln1329_1_reg_3117;
wire   [7:0] tlen_fu_1240_p2;
reg   [7:0] tlen_reg_3122;
wire   [63:0] zext_ln1323_fu_1246_p1;
reg   [63:0] zext_ln1323_reg_3128;
wire   [12:0] zext_ln1323_1_fu_1250_p1;
reg   [12:0] zext_ln1323_1_reg_3134;
wire   [8:0] zext_ln1323_2_fu_1254_p1;
reg   [8:0] zext_ln1323_2_reg_3140;
wire   [17:0] zext_ln1323_3_fu_1258_p1;
reg   [17:0] zext_ln1323_3_reg_3146;
wire   [11:0] shl_ln2467_2_fu_1266_p3;
reg   [11:0] shl_ln2467_2_reg_3154;
wire   [14:0] fk_fu_1286_p2;
reg   [14:0] fk_reg_3159;
wire   [12:0] zext_ln2467_fu_1302_p1;
reg   [12:0] zext_ln2467_reg_3164;
wire   [12:0] add_ln2467_fu_1306_p2;
reg   [12:0] add_ln2467_reg_3169;
wire   [14:0] t1_fu_1320_p2;
reg   [14:0] t1_reg_3175;
wire   [7:0] x_assign_fu_1326_p2;
reg   [7:0] x_assign_reg_3181;
wire   [31:0] x_assign_85_cast_fu_1332_p1;
reg   [31:0] x_assign_85_cast_reg_3186;
wire   [9:0] k_9_cast47_fu_1342_p1;
reg   [9:0] k_9_cast47_reg_3191;
wire   [31:0] zext_ln1330_fu_1362_p1;
reg   [31:0] zext_ln1330_reg_3196;
wire   [12:0] zext_ln2474_fu_1366_p1;
reg   [12:0] zext_ln2474_reg_3201;
wire   [63:0] zext_ln2474_1_fu_1378_p1;
reg   [63:0] zext_ln2474_1_reg_3207;
wire    ap_CS_fsm_state2;
wire   [11:0] zext_ln2474_2_fu_1383_p1;
reg   [11:0] zext_ln2474_2_reg_3212;
wire   [7:0] u_192_fu_1392_p2;
reg   [7:0] u_192_reg_3220;
wire   [0:0] icmp_ln2474_fu_1387_p2;
reg   [24:0] p_reg_3251;
wire    ap_CS_fsm_state3;
wire  signed [30:0] sext_ln1324_fu_1417_p1;
reg  signed [30:0] sext_ln1324_reg_3264;
wire  signed [30:0] y_56_fu_1461_p2;
reg  signed [30:0] y_56_reg_3271;
wire   [31:0] zext_ln1324_fu_1467_p1;
reg   [31:0] zext_ln1324_reg_3277;
wire   [30:0] p0i_fu_1503_p2;
reg   [30:0] p0i_reg_3286;
wire   [31:0] zext_ln1324_1_fu_1509_p1;
reg   [31:0] zext_ln1324_1_reg_3291;
wire   [31:0] z_83_fu_1514_p2;
reg   [31:0] z_83_reg_3296;
wire   [31:0] zext_ln757_9_fu_1610_p1;
reg   [31:0] zext_ln757_9_reg_3304;
wire    ap_CS_fsm_state8;
wire   [31:0] i_11_fu_1629_p2;
reg   [31:0] i_11_reg_3314;
wire   [3:0] k_12_fu_1657_p2;
wire   [31:0] e_fu_1663_p2;
reg   [31:0] e_reg_3335;
wire  signed [31:0] sext_ln808_fu_1668_p1;
reg  signed [31:0] sext_ln808_reg_3340;
wire   [5:0] i_12_fu_1680_p2;
reg   [5:0] i_12_reg_3348;
wire   [31:0] z_80_fu_1714_p2;
wire    ap_CS_fsm_state14;
wire   [10:0] u_190_fu_1729_p2;
reg   [10:0] u_190_reg_3361;
reg   [9:0] v_25_reg_3371;
wire   [10:0] v_26_fu_1822_p2;
reg   [10:0] v_26_reg_3379;
wire    ap_CS_fsm_state19;
wire   [9:0] trunc_ln2487_fu_1828_p1;
reg   [9:0] trunc_ln2487_reg_3384;
wire   [0:0] icmp_ln2485_fu_1817_p2;
wire   [11:0] add_ln2490_fu_1864_p2;
reg   [11:0] add_ln2490_reg_3394;
wire   [12:0] zext_ln2457_fu_1940_p1;
reg   [12:0] zext_ln2457_reg_3400;
wire    ap_CS_fsm_state21;
wire   [10:0] v_30_fu_1948_p2;
reg   [10:0] v_30_reg_3412;
wire    ap_CS_fsm_state22;
wire   [14:0] x_22_fu_1971_p2;
reg   [14:0] x_22_reg_3417;
wire   [0:0] icmp_ln2491_fu_1943_p2;
wire   [12:0] add_ln1524_fu_1980_p2;
reg   [12:0] add_ln1524_reg_3422;
wire   [14:0] x_19_fu_1997_p2;
reg   [14:0] x_19_reg_3428;
wire   [8:0] u_191_fu_2007_p2;
reg   [8:0] u_191_reg_3433;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln1520_fu_2046_p2;
reg   [0:0] icmp_ln1520_reg_3443;
wire   [31:0] x_26_fu_2132_p2;
reg   [31:0] x_26_reg_3447;
wire    ap_CS_fsm_state24;
reg   [12:0] lshr_ln55_reg_3458;
wire   [17:0] add_ln2491_1_fu_2179_p2;
reg   [17:0] add_ln2491_1_reg_3463;
wire   [17:0] add_ln2491_2_fu_2184_p2;
reg   [17:0] add_ln2491_2_reg_3468;
wire   [10:0] v_29_fu_2269_p2;
reg   [10:0] v_29_reg_3476;
wire    ap_CS_fsm_state27;
wire   [0:0] icmp_ln2497_fu_2264_p2;
reg   [12:0] vla18_addr_292_reg_3486;
wire   [17:0] add_ln2497_1_fu_2353_p2;
reg   [17:0] add_ln2497_1_reg_3492;
wire   [9:0] hm_fu_2374_p4;
reg   [9:0] hm_reg_3500;
wire    ap_CS_fsm_state30;
wire   [0:0] icmp_ln1339_fu_2368_p2;
wire   [10:0] zext_ln1343_fu_2384_p1;
reg   [10:0] zext_ln1343_reg_3505;
wire   [63:0] dt_fu_2388_p2;
reg   [63:0] dt_reg_3510;
wire   [11:0] zext_ln1345_fu_2394_p1;
reg   [11:0] zext_ln1345_reg_3516;
wire   [9:0] u_194_fu_2403_p2;
reg   [9:0] u_194_reg_3524;
wire    ap_CS_fsm_state31;
wire   [11:0] add_ln1351_1_fu_2418_p2;
reg   [11:0] add_ln1351_1_reg_3529;
wire   [0:0] icmp_ln1345_fu_2398_p2;
wire  signed [12:0] trunc_ln1345_fu_2423_p1;
wire    ap_CS_fsm_state33;
reg   [31:0] s_reg_3544;
wire    ap_CS_fsm_state34;
wire   [12:0] grp_fu_3000_p3;
reg  signed [12:0] add_ln1348_1_reg_3549;
wire   [12:0] grp_fu_3006_p4;
reg  signed [12:0] add_ln1348_3_reg_3554;
wire   [63:0] v_32_fu_2468_p2;
reg   [63:0] v_32_reg_3562;
wire    ap_CS_fsm_state35;
reg   [12:0] vla18_addr_297_reg_3567;
wire   [0:0] icmp_ln1354_fu_2462_p2;
reg   [12:0] vla18_addr_298_reg_3573;
wire   [63:0] add_ln1354_1_fu_2544_p2;
reg   [63:0] add_ln1354_1_reg_3579;
wire   [63:0] v1_1_fu_2549_p2;
wire   [10:0] k_13_fu_2648_p2;
reg   [10:0] k_13_reg_3592;
wire    ap_CS_fsm_state38;
reg   [12:0] vla18_addr_296_reg_3597;
wire   [0:0] icmp_ln1373_fu_2643_p2;
wire   [17:0] add_ln1373_1_fu_2691_p2;
reg   [17:0] add_ln1373_1_reg_3603;
wire   [63:0] u_112_cast_cast_cast_cast_fu_2703_p1;
reg   [63:0] u_112_cast_cast_cast_cast_reg_3608;
wire    ap_CS_fsm_state40;
wire   [31:0] zext_ln2513_fu_2712_p1;
reg   [31:0] zext_ln2513_reg_3614;
wire   [10:0] u_189_fu_2724_p2;
reg   [10:0] u_189_reg_3622;
wire    ap_CS_fsm_state41;
wire   [12:0] add_ln2281_fu_2734_p2;
reg   [12:0] add_ln2281_reg_3627;
wire   [0:0] icmp_ln2513_fu_2719_p2;
wire   [31:0] zext_ln2281_2_fu_2806_p1;
reg   [31:0] zext_ln2281_2_reg_3637;
wire    ap_CS_fsm_state42;
wire   [12:0] trunc_ln2297_fu_2810_p1;
reg   [12:0] trunc_ln2297_reg_3642;
wire   [0:0] icmp_ln2293_fu_2824_p2;
reg   [0:0] icmp_ln2293_reg_3650;
wire    ap_CS_fsm_state43;
wire   [0:0] icmp_ln2284_fu_2814_p2;
reg   [12:0] vla18_addr_285_reg_3660;
wire   [63:0] u_188_fu_2903_p2;
reg   [63:0] u_188_reg_3665;
wire   [30:0] trunc_ln2297_1_fu_2963_p1;
wire    ap_CS_fsm_state44;
wire    grp_modp_montymul_fu_800_ap_ready;
reg   [31:0] grp_modp_montymul_fu_800_a;
reg   [31:0] grp_modp_montymul_fu_800_b;
reg   [31:0] grp_modp_montymul_fu_800_p;
reg   [31:0] grp_modp_montymul_fu_800_p0i;
wire    grp_zint_rebuild_CRT_1_fu_1154_ap_start;
wire    grp_zint_rebuild_CRT_1_fu_1154_ap_done;
wire    grp_zint_rebuild_CRT_1_fu_1154_ap_idle;
wire    grp_zint_rebuild_CRT_1_fu_1154_ap_ready;
wire   [12:0] grp_zint_rebuild_CRT_1_fu_1154_vla18_address0;
wire    grp_zint_rebuild_CRT_1_fu_1154_vla18_ce0;
wire   [3:0] grp_zint_rebuild_CRT_1_fu_1154_vla18_we0;
wire   [31:0] grp_zint_rebuild_CRT_1_fu_1154_vla18_d0;
wire   [12:0] grp_zint_rebuild_CRT_1_fu_1154_vla18_address1;
wire    grp_zint_rebuild_CRT_1_fu_1154_vla18_ce1;
wire   [3:0] grp_zint_rebuild_CRT_1_fu_1154_vla18_we1;
wire   [31:0] grp_zint_rebuild_CRT_1_fu_1154_vla18_d1;
wire    grp_modp_NTT2_ext_1_fu_1171_ap_start;
wire    grp_modp_NTT2_ext_1_fu_1171_ap_done;
wire    grp_modp_NTT2_ext_1_fu_1171_ap_idle;
wire    grp_modp_NTT2_ext_1_fu_1171_ap_ready;
wire   [12:0] grp_modp_NTT2_ext_1_fu_1171_vla18_address0;
wire    grp_modp_NTT2_ext_1_fu_1171_vla18_ce0;
wire   [3:0] grp_modp_NTT2_ext_1_fu_1171_vla18_we0;
wire   [31:0] grp_modp_NTT2_ext_1_fu_1171_vla18_d0;
wire   [12:0] grp_modp_NTT2_ext_1_fu_1171_vla18_address1;
wire    grp_modp_NTT2_ext_1_fu_1171_vla18_ce1;
wire   [3:0] grp_modp_NTT2_ext_1_fu_1171_vla18_we1;
wire   [31:0] grp_modp_NTT2_ext_1_fu_1171_vla18_d1;
reg   [14:0] grp_modp_NTT2_ext_1_fu_1171_a;
reg   [7:0] grp_modp_NTT2_ext_1_fu_1171_stride;
reg   [31:0] i_reg_476;
wire   [31:0] ap_phi_mux_r_10_phi_fu_490_p4;
reg   [31:0] r_10_reg_487;
reg   [31:0] z_84_reg_497;
reg   [31:0] z_62_reg_507;
reg   [3:0] k_7_reg_519;
wire   [31:0] ap_phi_mux_g_assign_4_phi_fu_531_p4;
reg   [31:0] g_assign_4_reg_528;
reg  signed [5:0] i_9_reg_538;
wire   [31:0] ap_phi_mux_z_63_phi_fu_552_p4;
reg   [31:0] x2_reg_558;
wire    ap_CS_fsm_state18;
reg   [31:0] x1_2_reg_569;
reg   [10:0] u_116_reg_580;
reg   [10:0] v_021_reg_591;
wire    ap_CS_fsm_state20;
reg   [10:0] v_27_reg_602;
wire    ap_CS_fsm_state25;
reg   [17:0] idx_reg_613;
reg   [17:0] idx121_reg_625;
reg  signed [8:0] phi_ln1510_reg_637;
reg   [31:0] x_17_reg_646;
reg   [10:0] v_28_reg_657;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state29;
reg   [17:0] idx123_reg_668;
reg   [10:0] m_reg_679;
reg   [63:0] t_reg_688;
reg   [9:0] u_193_reg_712;
reg   [63:0] v_31_reg_723;
wire    ap_CS_fsm_state37;
reg   [63:0] idx127_reg_734;
reg   [10:0] k_10_reg_745;
wire    ap_CS_fsm_state39;
reg   [17:0] idx125_reg_756;
reg   [0:0] cc_reg_767;
wire   [31:0] z_fu_1561_p2;
wire   [31:0] zext_ln937_fu_1646_p1;
wire   [31:0] add_ln697_fu_2636_p2;
reg    grp_zint_rebuild_CRT_1_fu_1154_ap_start_reg;
reg    grp_modp_NTT2_ext_1_fu_1171_ap_start_reg;
wire   [63:0] zext_ln966_fu_1740_p1;
wire   [63:0] zext_ln967_1_fu_1772_p1;
wire   [63:0] zext_ln968_2_fu_1812_p1;
wire   [63:0] zext_ln2487_1_fu_1859_p1;
wire   [63:0] zext_ln2487_3_fu_1935_p1;
wire   [63:0] zext_ln1524_fu_2041_p1;
wire   [63:0] zext_ln1544_fu_2165_p1;
wire   [63:0] zext_ln2494_fu_2260_p1;
wire   [63:0] zext_ln2500_1_fu_2333_p1;
wire   [63:0] zext_ln2500_2_fu_2348_p1;
wire   [63:0] zext_ln1351_2_fu_2457_p1;
wire   [63:0] zext_ln1358_fu_2524_p1;
wire   [63:0] zext_ln1359_fu_2539_p1;
wire   [63:0] zext_ln1374_fu_2686_p1;
wire   [63:0] zext_ln2281_fu_2767_p1;
wire   [63:0] zext_ln2293_fu_2861_p1;
wire   [63:0] zext_ln2297_fu_2898_p1;
reg   [7:0] u_112_fu_222;
reg   [18:0] idx133_fu_226;
wire   [18:0] add_ln2513_1_fu_2909_p2;
reg   [17:0] idx131_fu_230;
wire   [17:0] add_ln2513_2_fu_2914_p2;
reg   [10:0] u_fu_234;
wire   [31:0] w_54_fu_1897_p2;
wire   [31:0] z_82_fu_2253_p2;
wire   [31:0] add_ln685_13_fu_2594_p2;
wire   [31:0] zext_ln2298_fu_2987_p1;
wire  signed [5:0] scl_cast_fu_1190_p0;
wire   [10:0] zext_ln2462_1_fu_1222_p1;
wire   [13:0] shl_ln_fu_1274_p3;
wire   [14:0] zext_ln2466_fu_1282_p1;
wire   [15:0] zext_ln1323_4_fu_1262_p1;
wire   [15:0] zext_ln2462_fu_1218_p1;
wire   [15:0] shl_ln2467_fu_1292_p2;
wire   [12:0] trunc_ln2467_fu_1298_p1;
wire   [14:0] shl_ln2467_1_fu_1312_p3;
wire   [2:0] empty_fu_1214_p1;
wire   [2:0] k_9_fu_1336_p2;
wire   [4:0] logn_cast4_fu_1210_p1;
wire   [4:0] sub_i92_fu_1346_p2;
wire   [25:0] sub_i92_cast_fu_1352_p1;
wire   [25:0] ni_fu_1356_p2;
wire  signed [24:0] trunc_ln1324_fu_1413_p0;
wire  signed [24:0] sext_ln1324_fu_1417_p0;
wire   [23:0] trunc_ln1324_fu_1413_p1;
wire   [23:0] y_54_fu_1421_p2;
wire  signed [24:0] mul_ln656_fu_1431_p0;
wire   [23:0] mul_ln656_fu_1431_p1;
wire   [30:0] zext_ln656_fu_1427_p1;
wire   [30:0] mul_ln656_fu_1431_p2;
wire  signed [30:0] y_55_fu_1443_p0;
wire   [23:0] y_55_fu_1443_p1;
wire  signed [24:0] mul_ln657_fu_1449_p0;
wire  signed [30:0] y_55_fu_1443_p2;
wire   [30:0] mul_ln657_fu_1449_p2;
wire  signed [30:0] y_56_fu_1461_p0;
wire  signed [24:0] mul_ln658_fu_1471_p0;
wire   [30:0] mul_ln658_fu_1471_p2;
wire  signed [30:0] y_57_fu_1481_p0;
wire  signed [24:0] mul_ln659_fu_1486_p0;
wire  signed [30:0] y_57_fu_1481_p2;
wire   [30:0] mul_ln659_fu_1486_p2;
wire  signed [30:0] p0i_fu_1503_p0;
wire  signed [30:0] p0i_fu_1503_p1;
wire   [31:0] shl_ln685_fu_1520_p2;
wire   [31:0] sub_ln685_fu_1526_p2;
wire   [0:0] tmp_171_fu_1532_p3;
wire   [24:0] select_ln685_fu_1540_p3;
wire   [24:0] and_ln685_fu_1548_p2;
wire  signed [30:0] sext_ln685_fu_1553_p1;
wire   [31:0] zext_ln685_fu_1557_p1;
wire   [0:0] trunc_ln735_fu_1569_p1;
wire   [24:0] select_ln757_fu_1573_p3;
wire   [24:0] and_ln757_fu_1581_p2;
wire  signed [30:0] sext_ln757_fu_1586_p1;
wire   [31:0] zext_ln757_fu_1590_p1;
wire   [31:0] add_ln757_fu_1594_p2;
wire   [30:0] R2_fu_1600_p4;
wire   [31:0] shl_ln779_fu_1614_p2;
wire   [7:0] trunc_ln779_fu_1620_p1;
wire   [7:0] and_ln781_fu_1635_p2;
wire   [31:0] xor_ln813_fu_1686_p1;
wire   [31:0] lshr_ln813_fu_1692_p2;
wire   [0:0] trunc_ln813_fu_1696_p1;
wire   [31:0] xor_ln813_fu_1686_p2;
wire   [31:0] select_ln813_fu_1700_p3;
wire   [31:0] and_ln813_fu_1708_p2;
wire   [31:0] z_80_fu_1714_p1;
wire   [9:0] trunc_ln962_fu_1720_p1;
wire   [9:0] shl_ln966_fu_1735_p2;
wire   [11:0] shl_ln47_fu_1745_p3;
wire   [14:0] zext_ln967_fu_1753_p1;
wire   [14:0] add_ln967_fu_1757_p2;
wire   [12:0] lshr_ln50_fu_1762_p4;
wire   [10:0] zext_ln968_fu_1777_p1;
wire   [10:0] add_ln968_fu_1780_p2;
wire   [12:0] shl_ln48_fu_1785_p3;
wire   [14:0] zext_ln968_1_fu_1793_p1;
wire   [14:0] add_ln968_1_fu_1797_p2;
wire   [12:0] lshr_ln51_fu_1802_p4;
wire   [11:0] shl_ln49_fu_1832_p3;
wire   [14:0] zext_ln2487_fu_1840_p1;
wire   [14:0] add_ln2487_fu_1844_p2;
wire   [12:0] lshr_ln52_fu_1849_p4;
wire   [0:0] tmp_174_fu_1868_p3;
wire   [24:0] select_ln635_fu_1876_p3;
wire   [24:0] and_ln635_fu_1884_p2;
wire  signed [30:0] sext_ln635_fu_1889_p1;
wire   [31:0] zext_ln635_fu_1893_p1;
wire   [12:0] zext_ln2487_2_fu_1904_p1;
wire   [12:0] add_ln2487_1_fu_1907_p2;
wire   [14:0] shl_ln2487_1_fu_1912_p3;
wire   [14:0] add_ln2487_2_fu_1920_p2;
wire   [12:0] lshr_ln2487_1_fu_1925_p4;
wire   [12:0] trunc_ln2457_1_fu_1954_p1;
wire   [12:0] add_ln2457_fu_1958_p2;
wire   [14:0] shl_ln51_fu_1963_p3;
wire   [12:0] trunc_ln2491_fu_1976_p1;
wire   [13:0] shl_ln50_fu_1986_p3;
wire   [14:0] zext_ln2490_fu_1993_p1;
wire  signed [12:0] sext_ln1510_fu_2003_p1;
wire   [12:0] add_ln1524_3_fu_2013_p2;
wire   [14:0] shl_ln52_fu_2018_p3;
wire   [14:0] add_ln1524_2_fu_2026_p2;
wire   [12:0] lshr_ln53_fu_2031_p4;
wire   [31:0] w_55_fu_2052_p2;
wire   [0:0] tmp_175_fu_2057_p3;
wire   [24:0] select_ln1525_fu_2065_p3;
wire   [24:0] and_ln1525_fu_2073_p2;
wire  signed [30:0] sext_ln1521_fu_2078_p1;
wire   [31:0] zext_ln1521_fu_2082_p1;
wire   [31:0] add_ln685_fu_2091_p2;
wire   [31:0] w_57_fu_2086_p2;
wire   [31:0] add_ln685_10_fu_2097_p2;
wire   [0:0] tmp_176_fu_2103_p3;
wire   [24:0] select_ln685_7_fu_2111_p3;
wire   [24:0] and_ln685_5_fu_2119_p2;
wire  signed [30:0] sext_ln685_5_fu_2124_p1;
wire   [31:0] zext_ln685_7_fu_2128_p1;
wire   [12:0] add_ln1544_fu_2138_p2;
wire   [14:0] shl_ln54_fu_2142_p3;
wire   [14:0] add_ln1544_2_fu_2150_p2;
wire   [12:0] lshr_ln1544_2_fu_2155_p4;
wire   [1:0] trunc_ln9_fu_2189_p4;
wire   [2:0] zext_ln1544_3_fu_2199_p1;
wire   [2:0] sub_ln1544_fu_2203_p2;
wire  signed [31:0] sext_ln1544_fu_2209_p1;
wire   [31:0] and_ln1544_fu_2213_p2;
wire   [31:0] sub_ln697_fu_2219_p2;
wire   [0:0] tmp_177_fu_2224_p3;
wire   [24:0] select_ln697_fu_2232_p3;
wire   [24:0] and_ln697_fu_2240_p2;
wire  signed [30:0] sext_ln697_fu_2245_p1;
wire   [31:0] zext_ln697_fu_2249_p1;
wire   [12:0] trunc_ln2457_2_fu_2275_p1;
wire   [12:0] add_ln2457_2_fu_2279_p2;
wire   [14:0] shl_ln2457_1_fu_2284_p3;
wire   [9:0] trunc_ln2500_fu_2297_p1;
wire   [12:0] zext_ln2500_fu_2301_p1;
wire   [12:0] add_ln2500_fu_2305_p2;
wire   [14:0] shl_ln53_fu_2310_p3;
wire   [14:0] add_ln2500_1_fu_2318_p2;
wire   [12:0] lshr_ln54_fu_2323_p4;
wire   [14:0] x_fu_2292_p2;
wire   [12:0] lshr_ln2500_1_fu_2338_p4;
wire   [9:0] tmp_178_fu_2358_p4;
wire   [11:0] zext_ln1351_fu_2409_p1;
wire   [11:0] add_ln1351_fu_2413_p2;
wire   [13:0] shl_ln56_fu_2431_p3;
wire   [14:0] zext_ln1351_1_fu_2438_p1;
wire   [14:0] add_ln1351_2_fu_2442_p2;
wire   [12:0] lshr_ln57_fu_2447_p4;
wire   [12:0] trunc_ln1348_fu_2474_p1;
(* use_dsp48 = "no" *) wire   [12:0] add_ln1348_fu_2478_p2;
wire   [14:0] shl_ln57_fu_2483_p3;
(* use_dsp48 = "no" *) wire   [12:0] add_ln1348_2_fu_2496_p2;
wire   [14:0] shl_ln1348_1_fu_2501_p3;
wire   [14:0] r1_fu_2491_p2;
wire   [12:0] lshr_ln58_fu_2514_p4;
wire   [14:0] r2_fu_2509_p2;
wire   [12:0] lshr_ln59_fu_2529_p4;
wire   [31:0] sub_ln685_4_fu_2554_p2;
wire   [31:0] add_ln685_12_fu_2559_p2;
wire   [0:0] tmp_179_fu_2565_p3;
wire   [24:0] select_ln685_8_fu_2573_p3;
wire   [24:0] and_ln685_6_fu_2581_p2;
wire  signed [30:0] sext_ln685_6_fu_2586_p1;
wire   [31:0] zext_ln685_8_fu_2590_p1;
wire   [31:0] sub_ln697_2_fu_2601_p2;
wire   [0:0] tmp_180_fu_2607_p3;
wire   [24:0] select_ln697_2_fu_2615_p3;
wire   [24:0] and_ln697_1_fu_2623_p2;
wire  signed [30:0] sext_ln697_1_fu_2628_p1;
wire   [31:0] zext_ln697_1_fu_2632_p1;
wire   [12:0] trunc_ln1329_fu_2654_p1;
wire   [12:0] add_ln1329_fu_2658_p2;
wire   [14:0] shl_ln55_fu_2663_p3;
wire   [14:0] r_13_fu_2671_p2;
wire   [12:0] lshr_ln56_fu_2676_p4;
wire  signed [31:0] u_112_cast_cast_cast_fu_2700_p1;
wire  signed [5:0] sub9_i_fu_2707_p1;
wire   [5:0] sub9_i_fu_2707_p2;
wire   [12:0] trunc_ln2457_fu_2730_p1;
wire   [12:0] add_ln2281_2_fu_2739_p2;
wire   [14:0] shl_ln44_fu_2744_p3;
wire   [14:0] add_ln2281_1_fu_2752_p2;
wire   [12:0] lshr_ln2281_1_fu_2757_p4;
wire   [1:0] trunc_ln_fu_2772_p4;
wire   [2:0] zext_ln2281_1_fu_2782_p1;
wire   [2:0] sub_ln2281_fu_2786_p2;
wire   [1:0] ysign_fu_2792_p4;
wire  signed [30:0] sext_ln2281_fu_2802_p1;
wire   [63:0] v_fu_2819_p2;
wire   [12:0] trunc_ln2293_fu_2829_p1;
wire   [12:0] add_ln2293_fu_2833_p2;
wire   [14:0] shl_ln45_fu_2838_p3;
wire   [14:0] add_ln2293_1_fu_2846_p2;
wire   [12:0] lshr_ln_fu_2851_p4;
wire   [12:0] trunc_ln2297_2_fu_2866_p1;
wire   [12:0] add_ln2297_fu_2870_p2;
wire   [14:0] shl_ln46_fu_2875_p3;
wire   [14:0] add_ln2297_1_fu_2883_p2;
wire   [12:0] lshr_ln49_fu_2888_p4;
wire   [31:0] wy_fu_2933_p3;
wire   [31:0] shl_ln2294_fu_2939_p2;
wire   [30:0] trunc_ln2294_fu_2944_p1;
wire   [30:0] wys_fu_2948_p1;
wire   [30:0] wys_fu_2948_p2;
wire   [31:0] tw_1_fu_2958_p2;
wire   [31:0] zext_ln2287_fu_2954_p1;
wire   [31:0] sub_ln2297_fu_2967_p2;
wire   [31:0] zext_ln2284_fu_2973_p1;
wire   [31:0] w_fu_2977_p2;
wire   [30:0] trunc_ln2287_fu_2983_p1;
wire   [7:0] grp_fu_3000_p1;
wire   [11:0] grp_fu_3000_p2;
wire   [12:0] grp_fu_3006_p1;
wire   [7:0] grp_fu_3006_p2;
wire   [11:0] grp_fu_3006_p3;
reg   [43:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
reg    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 44'd1;
#0 grp_zint_rebuild_CRT_1_fu_1154_ap_start_reg = 1'b0;
#0 grp_modp_NTT2_ext_1_fu_1171_ap_start_reg = 1'b0;
end

keygen_modp_mkgm2_1_REV10_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
REV10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(REV10_address0),
    .ce0(REV10_ce0),
    .q0(REV10_q0)
);

keygen_modp_montymul grp_modp_montymul_fu_800(
    .ap_ready(grp_modp_montymul_fu_800_ap_ready),
    .a(grp_modp_montymul_fu_800_a),
    .b(grp_modp_montymul_fu_800_b),
    .p(grp_modp_montymul_fu_800_p),
    .p0i(grp_modp_montymul_fu_800_p0i),
    .ap_return(grp_modp_montymul_fu_800_ap_return)
);

keygen_zint_rebuild_CRT_1 grp_zint_rebuild_CRT_1_fu_1154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zint_rebuild_CRT_1_fu_1154_ap_start),
    .ap_done(grp_zint_rebuild_CRT_1_fu_1154_ap_done),
    .ap_idle(grp_zint_rebuild_CRT_1_fu_1154_ap_idle),
    .ap_ready(grp_zint_rebuild_CRT_1_fu_1154_ap_ready),
    .vla18_address0(grp_zint_rebuild_CRT_1_fu_1154_vla18_address0),
    .vla18_ce0(grp_zint_rebuild_CRT_1_fu_1154_vla18_ce0),
    .vla18_we0(grp_zint_rebuild_CRT_1_fu_1154_vla18_we0),
    .vla18_d0(grp_zint_rebuild_CRT_1_fu_1154_vla18_d0),
    .vla18_q0(vla18_q0),
    .vla18_address1(grp_zint_rebuild_CRT_1_fu_1154_vla18_address1),
    .vla18_ce1(grp_zint_rebuild_CRT_1_fu_1154_vla18_ce1),
    .vla18_we1(grp_zint_rebuild_CRT_1_fu_1154_vla18_we1),
    .vla18_d1(grp_zint_rebuild_CRT_1_fu_1154_vla18_d1),
    .vla18_q1(vla18_q1),
    .xx(fk_reg_3159),
    .xlen(zext_ln1323_2_reg_3140),
    .xstride(zext_ln1323_2_reg_3140),
    .num(zext_ln1329_reg_3112),
    .normalize_signed(1'd1),
    .tmp(t1_reg_3175)
);

keygen_modp_NTT2_ext_1 grp_modp_NTT2_ext_1_fu_1171(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_modp_NTT2_ext_1_fu_1171_ap_start),
    .ap_done(grp_modp_NTT2_ext_1_fu_1171_ap_done),
    .ap_idle(grp_modp_NTT2_ext_1_fu_1171_ap_idle),
    .ap_ready(grp_modp_NTT2_ext_1_fu_1171_ap_ready),
    .vla18_address0(grp_modp_NTT2_ext_1_fu_1171_vla18_address0),
    .vla18_ce0(grp_modp_NTT2_ext_1_fu_1171_vla18_ce0),
    .vla18_we0(grp_modp_NTT2_ext_1_fu_1171_vla18_we0),
    .vla18_d0(grp_modp_NTT2_ext_1_fu_1171_vla18_d0),
    .vla18_q0(vla18_q0),
    .vla18_address1(grp_modp_NTT2_ext_1_fu_1171_vla18_address1),
    .vla18_ce1(grp_modp_NTT2_ext_1_fu_1171_vla18_ce1),
    .vla18_we1(grp_modp_NTT2_ext_1_fu_1171_vla18_we1),
    .vla18_d1(grp_modp_NTT2_ext_1_fu_1171_vla18_d1),
    .vla18_q1(vla18_q1),
    .a(grp_modp_NTT2_ext_1_fu_1171_a),
    .stride(grp_modp_NTT2_ext_1_fu_1171_stride),
    .gm(tmp),
    .logn(logn_cast7_reg_3090),
    .p(p_reg_3251),
    .p0i(p0i_reg_3286)
);

keygen_mul_25s_24ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 31 ))
mul_25s_24ns_31_1_1_U378(
    .din0(mul_ln656_fu_1431_p0),
    .din1(mul_ln656_fu_1431_p1),
    .dout(mul_ln656_fu_1431_p2)
);

keygen_mul_31s_24ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 31 ))
mul_31s_24ns_31_1_1_U379(
    .din0(y_55_fu_1443_p0),
    .din1(y_55_fu_1443_p1),
    .dout(y_55_fu_1443_p2)
);

keygen_mul_25s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_25s_31s_31_1_1_U380(
    .din0(mul_ln657_fu_1449_p0),
    .din1(y_55_fu_1443_p2),
    .dout(mul_ln657_fu_1449_p2)
);

keygen_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U381(
    .din0(y_56_fu_1461_p0),
    .din1(y_55_fu_1443_p2),
    .dout(y_56_fu_1461_p2)
);

keygen_mul_25s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_25s_31s_31_1_1_U382(
    .din0(mul_ln658_fu_1471_p0),
    .din1(y_56_reg_3271),
    .dout(mul_ln658_fu_1471_p2)
);

keygen_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U383(
    .din0(y_57_fu_1481_p0),
    .din1(y_56_reg_3271),
    .dout(y_57_fu_1481_p2)
);

keygen_mul_25s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_25s_31s_31_1_1_U384(
    .din0(mul_ln659_fu_1486_p0),
    .din1(y_57_fu_1481_p2),
    .dout(mul_ln659_fu_1486_p2)
);

keygen_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U385(
    .din0(p0i_fu_1503_p0),
    .din1(p0i_fu_1503_p1),
    .dout(p0i_fu_1503_p2)
);

keygen_mac_muladd_13s_8ns_12ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 13 ))
mac_muladd_13s_8ns_12ns_13_4_1_U386(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln1345_fu_2423_p1),
    .din1(grp_fu_3000_p1),
    .din2(grp_fu_3000_p2),
    .ce(1'b1),
    .dout(grp_fu_3000_p3)
);

keygen_ama_addmuladd_13s_13ns_8ns_12ns_13_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 12 ),
    .dout_WIDTH( 13 ))
ama_addmuladd_13s_13ns_8ns_12ns_13_4_1_U387(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln1345_fu_2423_p1),
    .din1(grp_fu_3006_p1),
    .din2(grp_fu_3006_p2),
    .din3(grp_fu_3006_p3),
    .ce(1'b1),
    .dout(grp_fu_3006_p4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_modp_NTT2_ext_1_fu_1171_ap_start_reg <= 1'b0;
    end else begin
        if ((((icmp_ln2491_fu_1943_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((icmp_ln2485_fu_1817_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19)))) begin
            grp_modp_NTT2_ext_1_fu_1171_ap_start_reg <= 1'b1;
        end else if ((grp_modp_NTT2_ext_1_fu_1171_ap_ready == 1'b1)) begin
            grp_modp_NTT2_ext_1_fu_1171_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zint_rebuild_CRT_1_fu_1154_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln2474_fu_1387_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_zint_rebuild_CRT_1_fu_1154_ap_start_reg <= 1'b1;
        end else if ((grp_zint_rebuild_CRT_1_fu_1154_ap_ready == 1'b1)) begin
            grp_zint_rebuild_CRT_1_fu_1154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        cc_reg_767 <= w_fu_2977_p2[32'd31];
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        cc_reg_767 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        i_9_reg_538 <= i_12_reg_3348;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd0))) begin
        i_9_reg_538 <= 6'd30;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_reg_476 <= i_11_reg_3314;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i_reg_476 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_modp_NTT2_ext_1_fu_1171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        idx121_reg_625 <= 18'd0;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        idx121_reg_625 <= add_ln2491_2_reg_3468;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        idx123_reg_668 <= add_ln2497_1_reg_3492;
    end else if (((grp_modp_NTT2_ext_1_fu_1171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        idx123_reg_668 <= 18'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1339_fu_2368_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
        idx125_reg_756 <= 18'd0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        idx125_reg_756 <= add_ln1373_1_reg_3603;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        idx127_reg_734 <= add_ln1354_1_reg_3579;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        idx127_reg_734 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2474_fu_1387_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        idx131_fu_230 <= 18'd0;
    end else if (((icmp_ln2284_fu_2814_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state43))) begin
        idx131_fu_230 <= add_ln2513_2_fu_2914_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2474_fu_1387_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        idx133_fu_226 <= 19'd0;
    end else if (((icmp_ln2284_fu_2814_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state43))) begin
        idx133_fu_226 <= add_ln2513_1_fu_2909_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_modp_NTT2_ext_1_fu_1171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        idx_reg_613 <= 18'd0;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        idx_reg_613 <= add_ln2491_1_reg_3463;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1339_fu_2368_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
        k_10_reg_745 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        k_10_reg_745 <= k_13_reg_3592;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd1))) begin
        k_7_reg_519 <= k_12_fu_1657_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        k_7_reg_519 <= logn;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2497_fu_2264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state27))) begin
        m_reg_679 <= m_4_reg_3100;
    end else if (((icmp_ln1345_fu_2398_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state31))) begin
        m_reg_679 <= zext_ln1343_reg_3505;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2491_fu_1943_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        phi_ln1510_reg_637 <= flen_cast14_reg_3080;
    end else if (((icmp_ln1520_reg_3443 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        phi_ln1510_reg_637 <= u_191_reg_3433;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r_10_reg_487 <= grp_modp_montymul_fu_800_ap_return;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        r_10_reg_487 <= zext_ln757_9_fu_1610_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_549 <= z_80_fu_1714_p2;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd0))) begin
        reg_549 <= z_83_reg_3296;
    end else if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_549 <= grp_modp_montymul_fu_800_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1354_fu_2462_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state35))) begin
        reg_700 <= v1_1_fu_2549_p2;
    end else if (((icmp_ln1339_fu_2368_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
        reg_700 <= 64'd0;
    end else if ((((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd1)) | ((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd0)))) begin
        reg_700 <= grp_modp_montymul_fu_800_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        reg_779 <= trunc_ln2297_1_fu_2963_p1;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        reg_779 <= 31'd0;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln781_fu_1640_p2 == 1'd0) & (icmp_ln779_fu_1624_p2 == 1'd0))) begin
        reg_779 <= grp_modp_montymul_fu_800_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        reg_791 <= u_188_reg_3665;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        reg_791 <= u_112_cast_cast_cast_cast_reg_3608;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_791 <= grp_modp_montymul_fu_800_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2497_fu_2264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state27))) begin
        t_reg_688 <= 64'd1;
    end else if (((icmp_ln1345_fu_2398_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state31))) begin
        t_reg_688 <= dt_reg_3510;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        u_112_fu_222 <= 8'd0;
    end else if (((icmp_ln1373_fu_2643_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state38))) begin
        u_112_fu_222 <= u_192_reg_3220;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        u_116_reg_580 <= u_190_reg_3361;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        u_116_reg_580 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1354_fu_2462_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state35))) begin
        u_193_reg_712 <= u_194_reg_3524;
    end else if (((icmp_ln1339_fu_2368_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
        u_193_reg_712 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2474_fu_1387_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        u_fu_234 <= 11'd0;
    end else if (((icmp_ln2284_fu_2814_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state43))) begin
        u_fu_234 <= u_189_reg_3622;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln962_fu_1724_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        v_021_reg_591 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        v_021_reg_591 <= v_26_reg_3379;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_modp_NTT2_ext_1_fu_1171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        v_27_reg_602 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        v_27_reg_602 <= v_30_reg_3412;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        v_28_reg_657 <= v_29_reg_3476;
    end else if (((grp_modp_NTT2_ext_1_fu_1171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        v_28_reg_657 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        v_31_reg_723 <= v_32_reg_3562;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        v_31_reg_723 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        x1_2_reg_569 <= x1_3_reg_1021;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x1_2_reg_569 <= z_83_reg_3296;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        x2_reg_558 <= x2_2_reg_1054;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x2_reg_558 <= z_83_reg_3296;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2491_fu_1943_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        x_17_reg_646 <= 32'd0;
    end else if (((icmp_ln1520_reg_3443 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        x_17_reg_646 <= x_26_fu_2132_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln779_fu_1624_p2 == 1'd0))) begin
        if ((icmp_ln781_fu_1640_p2 == 1'd1)) begin
            z_62_reg_507 <= z_84_reg_497;
        end else if ((icmp_ln781_fu_1640_p2 == 1'd0)) begin
            z_62_reg_507 <= grp_modp_montymul_fu_800_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        z_84_reg_497 <= z_62_reg_507;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        z_84_reg_497 <= z_83_reg_3296;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Fstride_cast_reg_3095[8 : 0] <= Fstride_cast_fu_1206_p1[8 : 0];
        add_ln2467_reg_3169 <= add_ln2467_fu_1306_p2;
        fk_reg_3159 <= fk_fu_1286_p2;
        flen_cast14_reg_3080[7 : 0] <= flen_cast14_fu_1194_p1[7 : 0];
        fstride_cast_reg_3085[7 : 0] <= fstride_cast_fu_1198_p1[7 : 0];
        k_9_cast47_reg_3191[2 : 0] <= k_9_cast47_fu_1342_p1[2 : 0];
        logn_cast7_reg_3090[3 : 0] <= logn_cast7_fu_1202_p1[3 : 0];
        m_4_reg_3100 <= m_4_fu_1226_p2;
        scl_cast_reg_3075 <= scl_cast_fu_1190_p1;
        shl_ln2467_2_reg_3154[11 : 1] <= shl_ln2467_2_fu_1266_p3[11 : 1];
        t1_reg_3175 <= t1_fu_1320_p2;
        tlen_reg_3122 <= tlen_fu_1240_p2;
        x_assign_85_cast_reg_3186[7 : 0] <= x_assign_85_cast_fu_1332_p1[7 : 0];
        x_assign_reg_3181 <= x_assign_fu_1326_p2;
        zext_ln1323_1_reg_3134[7 : 0] <= zext_ln1323_1_fu_1250_p1[7 : 0];
        zext_ln1323_2_reg_3140[7 : 0] <= zext_ln1323_2_fu_1254_p1[7 : 0];
        zext_ln1323_3_reg_3146[7 : 0] <= zext_ln1323_3_fu_1258_p1[7 : 0];
        zext_ln1323_reg_3128[7 : 0] <= zext_ln1323_fu_1246_p1[7 : 0];
        zext_ln1329_1_reg_3117[10 : 0] <= zext_ln1329_1_fu_1236_p1[10 : 0];
        zext_ln1329_reg_3112[10 : 0] <= zext_ln1329_fu_1232_p1[10 : 0];
        zext_ln1330_reg_3196[25 : 0] <= zext_ln1330_fu_1362_p1[25 : 0];
        zext_ln2467_reg_3164[11 : 1] <= zext_ln2467_fu_1302_p1[11 : 1];
        zext_ln2474_reg_3201[7 : 0] <= zext_ln2474_fu_1366_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        add_ln1348_1_reg_3549 <= grp_fu_3000_p3;
        add_ln1348_3_reg_3554 <= grp_fu_3006_p4;
        s_reg_3544 <= vla18_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1345_fu_2398_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state31))) begin
        add_ln1351_1_reg_3529 <= add_ln1351_1_fu_2418_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1354_fu_2462_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state35))) begin
        add_ln1354_1_reg_3579 <= add_ln1354_1_fu_2544_p2;
        vla18_addr_297_reg_3567 <= zext_ln1358_fu_2524_p1;
        vla18_addr_298_reg_3573 <= zext_ln1359_fu_2539_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1373_fu_2643_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state38))) begin
        add_ln1373_1_reg_3603 <= add_ln1373_1_fu_2691_p2;
        vla18_addr_296_reg_3597 <= zext_ln1374_fu_2686_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2491_fu_1943_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
        add_ln1524_reg_3422 <= add_ln1524_fu_1980_p2;
        x_22_reg_3417 <= x_22_fu_1971_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2513_fu_2719_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state41))) begin
        add_ln2281_reg_3627 <= add_ln2281_fu_2734_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2485_fu_1817_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
        add_ln2490_reg_3394 <= add_ln2490_fu_1864_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1520_reg_3443 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        add_ln2491_1_reg_3463 <= add_ln2491_1_fu_2179_p2;
        add_ln2491_2_reg_3468 <= add_ln2491_2_fu_2184_p2;
        lshr_ln55_reg_3458 <= {{x_22_reg_3417[14:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2497_fu_2264_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state27))) begin
        add_ln2497_1_reg_3492 <= add_ln2497_1_fu_2353_p2;
        vla18_addr_292_reg_3486 <= zext_ln2500_2_fu_2348_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1339_fu_2368_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state30))) begin
        dt_reg_3510[63 : 1] <= dt_fu_2388_p2[63 : 1];
        hm_reg_3500 <= {{m_reg_679[10:1]}};
        zext_ln1343_reg_3505[9 : 0] <= zext_ln1343_fu_2384_p1[9 : 0];
        zext_ln1345_reg_3516[9 : 0] <= zext_ln1345_fu_2394_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd0))) begin
        e_reg_3335 <= e_fu_1663_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd1)))) begin
        g_assign_4_reg_528 <= grp_modp_montymul_fu_800_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_11_reg_3314 <= i_11_fu_1629_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd0))) begin
        i_12_reg_3348 <= i_12_fu_1680_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        icmp_ln1520_reg_3443 <= icmp_ln1520_fu_2046_p2;
        u_191_reg_3433 <= u_191_fu_2007_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2284_fu_2814_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state43))) begin
        icmp_ln2293_reg_3650 <= icmp_ln2293_fu_2824_p2;
        u_188_reg_3665 <= u_188_fu_2903_p2;
        vla18_addr_285_reg_3660 <= zext_ln2297_fu_2898_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        k_13_reg_3592 <= k_13_fu_2648_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p0i_reg_3286 <= p0i_fu_1503_p2;
        z_83_reg_3296 <= z_83_fu_1514_p2;
        zext_ln1324_1_reg_3291[30 : 0] <= zext_ln1324_1_fu_1509_p1[30 : 0];
        zext_ln1324_reg_3277[30 : 0] <= zext_ln1324_fu_1467_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_reg_3251 <= PRIMES_p_q0;
        sext_ln1324_reg_3264 <= sext_ln1324_fu_1417_p1;
        y_56_reg_3271 <= y_56_fu_1461_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        sext_ln808_reg_3340 <= sext_ln808_fu_1668_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        trunc_ln2297_reg_3642 <= trunc_ln2297_fu_2810_p1;
        zext_ln2281_2_reg_3637[30 : 0] <= zext_ln2281_2_fu_2806_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2485_fu_1817_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        trunc_ln2487_reg_3384 <= trunc_ln2487_fu_1828_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        u_112_cast_cast_cast_cast_reg_3608[31 : 0] <= u_112_cast_cast_cast_cast_fu_2703_p1[31 : 0];
        zext_ln2513_reg_3614[5 : 0] <= zext_ln2513_fu_2712_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        u_189_reg_3622 <= u_189_fu_2724_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        u_190_reg_3361 <= u_190_fu_1729_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        u_192_reg_3220 <= u_192_fu_1392_p2;
        zext_ln2474_1_reg_3207[7 : 0] <= zext_ln2474_1_fu_1378_p1[7 : 0];
        zext_ln2474_2_reg_3212[7 : 0] <= zext_ln2474_2_fu_1383_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        u_194_reg_3524 <= u_194_fu_2403_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        v_25_reg_3371 <= REV10_q0;
        x2_2_reg_1054 <= grp_modp_montymul_fu_800_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        v_26_reg_3379 <= v_26_fu_1822_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        v_29_reg_3476 <= v_29_fu_2269_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        v_30_reg_3412 <= v_30_fu_1948_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        v_32_reg_3562 <= v_32_fu_2468_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln962_fu_1724_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        x1_3_reg_1021 <= grp_modp_montymul_fu_800_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln2491_fu_1943_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        x_19_reg_3428 <= x_19_fu_1997_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        x_26_reg_3447 <= x_26_fu_2132_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        zext_ln2457_reg_3400[11 : 0] <= zext_ln2457_fu_1940_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        zext_ln757_9_reg_3304[30 : 0] <= zext_ln757_9_fu_1610_p1[30 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        PRIMES_g_ce0 = 1'b1;
    end else begin
        PRIMES_g_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2474_fu_1387_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        PRIMES_p_address0 = zext_ln2474_1_fu_1378_p1;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        PRIMES_p_address0 = 10'd0;
    end else begin
        PRIMES_p_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln2474_fu_1387_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        PRIMES_p_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        PRIMES_p_ce0 = 1'b0;
    end else begin
        PRIMES_p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        REV10_ce0 = 1'b1;
    end else begin
        REV10_ce0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_modp_NTT2_ext_1_fu_1171_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((grp_modp_NTT2_ext_1_fu_1171_ap_done == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_zint_rebuild_CRT_1_fu_1154_ap_done == 1'b0)) begin
        ap_ST_fsm_state40_blk = 1'b1;
    end else begin
        ap_ST_fsm_state40_blk = 1'b0;
    end
end

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln2513_fu_2719_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state41)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2513_fu_2719_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_modp_NTT2_ext_1_fu_1171_a = x_19_reg_3428;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_modp_NTT2_ext_1_fu_1171_a = t1_reg_3175;
    end else begin
        grp_modp_NTT2_ext_1_fu_1171_a = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_modp_NTT2_ext_1_fu_1171_stride = tlen_reg_3122;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_modp_NTT2_ext_1_fu_1171_stride = 8'd1;
    end else begin
        grp_modp_NTT2_ext_1_fu_1171_stride = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_modp_montymul_fu_800_a = add_ln697_fu_2636_p2;
    end else if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state28))) begin
        grp_modp_montymul_fu_800_a = vla18_q1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_modp_montymul_fu_800_a = x_17_reg_646;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_modp_montymul_fu_800_a = x2_reg_558;
    end else if (((icmp_ln962_fu_1724_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        grp_modp_montymul_fu_800_a = x1_2_reg_569;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_modp_montymul_fu_800_a = zext_ln757_9_reg_3304;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_modp_montymul_fu_800_a = reg_700;
    end else if ((((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd1)) | ((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd0)))) begin
        grp_modp_montymul_fu_800_a = ap_phi_mux_z_63_phi_fu_552_p4;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd1))) begin
        grp_modp_montymul_fu_800_a = g_assign_4_reg_528;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_modp_montymul_fu_800_a = zext_ln937_fu_1646_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_modp_montymul_fu_800_a = r_10_reg_487;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln781_fu_1640_p2 == 1'd0) & (icmp_ln779_fu_1624_p2 == 1'd0))) begin
        grp_modp_montymul_fu_800_a = z_84_reg_497;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_modp_montymul_fu_800_a = reg_549;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_modp_montymul_fu_800_a = z_fu_1561_p2;
    end else begin
        grp_modp_montymul_fu_800_a = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_modp_montymul_fu_800_b = zext_ln1330_reg_3196;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_modp_montymul_fu_800_b = s_reg_3544;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        grp_modp_montymul_fu_800_b = vla18_q0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_modp_montymul_fu_800_b = reg_700;
    end else if (((1'b1 == ap_CS_fsm_state14) | ((icmp_ln962_fu_1724_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16)))) begin
        grp_modp_montymul_fu_800_b = g_assign_4_reg_528;
    end else if (((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd1))) begin
        grp_modp_montymul_fu_800_b = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd0))) begin
        grp_modp_montymul_fu_800_b = ap_phi_mux_z_63_phi_fu_552_p4;
    end else if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd1))) begin
        grp_modp_montymul_fu_800_b = ap_phi_mux_g_assign_4_phi_fu_531_p4;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state11))) begin
        grp_modp_montymul_fu_800_b = zext_ln757_9_reg_3304;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_modp_montymul_fu_800_b = r_10_reg_487;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln781_fu_1640_p2 == 1'd0) & (icmp_ln779_fu_1624_p2 == 1'd0))) begin
        grp_modp_montymul_fu_800_b = ap_phi_mux_r_10_phi_fu_490_p4;
    end else if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_modp_montymul_fu_800_b = reg_549;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_modp_montymul_fu_800_b = z_fu_1561_p2;
    end else begin
        grp_modp_montymul_fu_800_b = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((icmp_ln962_fu_1724_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16)) | ((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln781_fu_1640_p2 == 1'd0) & (icmp_ln779_fu_1624_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd1)) | ((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd0)))) begin
        grp_modp_montymul_fu_800_p = zext_ln1324_reg_3277;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_modp_montymul_fu_800_p = zext_ln1324_fu_1467_p1;
    end else begin
        grp_modp_montymul_fu_800_p = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | ((icmp_ln962_fu_1724_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16)) | ((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln781_fu_1640_p2 == 1'd0) & (icmp_ln779_fu_1624_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd1)) | ((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd0)))) begin
        grp_modp_montymul_fu_800_p0i = zext_ln1324_1_reg_3291;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_modp_montymul_fu_800_p0i = zext_ln1324_1_fu_1509_p1;
    end else begin
        grp_modp_montymul_fu_800_p0i = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        vla18_address0 = vla18_addr_285_reg_3660;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        vla18_address0 = zext_ln2297_fu_2898_p1;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        vla18_address0 = zext_ln1358_fu_2524_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        vla18_address0 = zext_ln2500_2_fu_2348_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        vla18_address0 = zext_ln2494_fu_2260_p1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        vla18_address0 = zext_ln1544_fu_2165_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        vla18_address0 = zext_ln1524_fu_2041_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        vla18_address0 = zext_ln2487_3_fu_1935_p1;
    end else if (((icmp_ln2485_fu_1817_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        vla18_address0 = zext_ln2487_1_fu_1859_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        vla18_address0 = zext_ln968_2_fu_1812_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        vla18_address0 = zext_ln967_1_fu_1772_p1;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state21))) begin
        vla18_address0 = grp_modp_NTT2_ext_1_fu_1171_vla18_address0;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        vla18_address0 = grp_zint_rebuild_CRT_1_fu_1154_vla18_address0;
    end else begin
        vla18_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        vla18_address1 = zext_ln2293_fu_2861_p1;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        vla18_address1 = zext_ln2281_fu_2767_p1;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        vla18_address1 = vla18_addr_296_reg_3597;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        vla18_address1 = zext_ln1374_fu_2686_p1;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        vla18_address1 = vla18_addr_298_reg_3573;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        vla18_address1 = vla18_addr_297_reg_3567;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        vla18_address1 = zext_ln1359_fu_2539_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        vla18_address1 = zext_ln1351_2_fu_2457_p1;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        vla18_address1 = vla18_addr_292_reg_3486;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        vla18_address1 = zext_ln2500_1_fu_2333_p1;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state21))) begin
        vla18_address1 = grp_modp_NTT2_ext_1_fu_1171_vla18_address1;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        vla18_address1 = grp_zint_rebuild_CRT_1_fu_1154_vla18_address1;
    end else begin
        vla18_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state17) | ((icmp_ln2485_fu_1817_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19)))) begin
        vla18_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state21))) begin
        vla18_ce0 = grp_modp_NTT2_ext_1_fu_1171_vla18_ce0;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        vla18_ce0 = grp_zint_rebuild_CRT_1_fu_1154_vla18_ce0;
    end else begin
        vla18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state36))) begin
        vla18_ce1 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state21))) begin
        vla18_ce1 = grp_modp_NTT2_ext_1_fu_1171_vla18_ce1;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        vla18_ce1 = grp_zint_rebuild_CRT_1_fu_1154_vla18_ce1;
    end else begin
        vla18_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        vla18_d0 = zext_ln2298_fu_2987_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        vla18_d0 = z_82_fu_2253_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        vla18_d0 = w_54_fu_1897_p2;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        vla18_d0 = x2_reg_558;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        vla18_d0 = x1_2_reg_569;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state21))) begin
        vla18_d0 = grp_modp_NTT2_ext_1_fu_1171_vla18_d0;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        vla18_d0 = grp_zint_rebuild_CRT_1_fu_1154_vla18_d0;
    end else begin
        vla18_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        vla18_d1 = reg_549;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        vla18_d1 = add_ln685_13_fu_2594_p2;
    end else if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state29))) begin
        vla18_d1 = grp_modp_montymul_fu_800_ap_return;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state21))) begin
        vla18_d1 = grp_modp_NTT2_ext_1_fu_1171_vla18_d1;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        vla18_d1 = grp_zint_rebuild_CRT_1_fu_1154_vla18_d1;
    end else begin
        vla18_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state17))) begin
        vla18_we0 = 4'd15;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state21))) begin
        vla18_we0 = grp_modp_NTT2_ext_1_fu_1171_vla18_we0;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        vla18_we0 = grp_zint_rebuild_CRT_1_fu_1154_vla18_we0;
    end else begin
        vla18_we0 = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state36))) begin
        vla18_we1 = 4'd15;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state21))) begin
        vla18_we1 = grp_modp_NTT2_ext_1_fu_1171_vla18_we1;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        vla18_we1 = grp_zint_rebuild_CRT_1_fu_1154_vla18_we1;
    end else begin
        vla18_we1 = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln2474_fu_1387_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln779_fu_1624_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln954_fu_1651_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (tmp_173_fu_1672_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln962_fu_1724_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state19 : begin
            if (((icmp_ln2485_fu_1817_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_modp_NTT2_ext_1_fu_1171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((icmp_ln2491_fu_1943_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((icmp_ln1520_reg_3443 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state26 : begin
            if (((grp_modp_NTT2_ext_1_fu_1171_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((icmp_ln2497_fu_2264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state30 : begin
            if (((icmp_ln1339_fu_2368_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state31 : begin
            if (((icmp_ln1345_fu_2398_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            if (((icmp_ln1354_fu_2462_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state38 : begin
            if (((icmp_ln1373_fu_2643_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state40 : begin
            if (((grp_zint_rebuild_CRT_1_fu_1154_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state41 : begin
            if (((icmp_ln2513_fu_2719_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            if (((icmp_ln2284_fu_2814_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state43))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Fstride_cast_fu_1206_p1 = Fstride;

assign PRIMES_g_address0 = zext_ln2474_1_reg_3207;

assign R2_fu_1600_p4 = {{add_ln757_fu_1594_p2[31:1]}};

assign REV10_address0 = zext_ln966_fu_1740_p1;

assign add_ln1329_fu_2658_p2 = (trunc_ln1329_fu_2654_p1 + zext_ln2457_reg_3400);

assign add_ln1348_2_fu_2496_p2 = ($signed(add_ln1348_3_reg_3554) + $signed(trunc_ln1348_fu_2474_p1));

assign add_ln1348_fu_2478_p2 = ($signed(add_ln1348_1_reg_3549) + $signed(trunc_ln1348_fu_2474_p1));

assign add_ln1351_1_fu_2418_p2 = (add_ln1351_fu_2413_p2 + zext_ln1345_reg_3516);

assign add_ln1351_2_fu_2442_p2 = (zext_ln1351_1_fu_2438_p1 + tmp);

assign add_ln1351_fu_2413_p2 = (zext_ln1329_1_reg_3117 + zext_ln1351_fu_2409_p1);

assign add_ln1354_1_fu_2544_p2 = (zext_ln1323_reg_3128 + idx127_reg_734);

assign add_ln1373_1_fu_2691_p2 = (zext_ln1323_3_reg_3146 + idx125_reg_756);

assign add_ln1524_2_fu_2026_p2 = (shl_ln52_fu_2018_p3 + f_r);

assign add_ln1524_3_fu_2013_p2 = ($signed(add_ln1524_reg_3422) + $signed(sext_ln1510_fu_2003_p1));

assign add_ln1524_fu_1980_p2 = ($signed(trunc_ln2491_fu_1976_p1) + $signed(13'd8191));

assign add_ln1544_2_fu_2150_p2 = (shl_ln54_fu_2142_p3 + f_r);

assign add_ln1544_fu_2138_p2 = (add_ln1524_reg_3422 + zext_ln2474_reg_3201);

assign add_ln2281_1_fu_2752_p2 = (shl_ln44_fu_2744_p3 + tmp);

assign add_ln2281_2_fu_2739_p2 = (add_ln2281_fu_2734_p2 + zext_ln2474_reg_3201);

assign add_ln2281_fu_2734_p2 = (trunc_ln2457_fu_2730_p1 + zext_ln2467_reg_3164);

assign add_ln2293_1_fu_2846_p2 = (shl_ln45_fu_2838_p3 + tmp);

assign add_ln2293_fu_2833_p2 = (trunc_ln2293_fu_2829_p1 + add_ln2281_reg_3627);

assign add_ln2297_1_fu_2883_p2 = (shl_ln46_fu_2875_p3 + F);

assign add_ln2297_fu_2870_p2 = (trunc_ln2297_2_fu_2866_p1 + trunc_ln2297_reg_3642);

assign add_ln2457_2_fu_2279_p2 = (trunc_ln2457_2_fu_2275_p1 + zext_ln2457_reg_3400);

assign add_ln2457_fu_1958_p2 = (trunc_ln2457_1_fu_1954_p1 + zext_ln2457_reg_3400);

assign add_ln2467_fu_1306_p2 = (zext_ln2467_fu_1302_p1 + trunc_ln2467_fu_1298_p1);

assign add_ln2487_1_fu_1907_p2 = (zext_ln2487_2_fu_1904_p1 + add_ln2467_reg_3169);

assign add_ln2487_2_fu_1920_p2 = (shl_ln2487_1_fu_1912_p3 + tmp);

assign add_ln2487_fu_1844_p2 = (zext_ln2487_fu_1840_p1 + k);

assign add_ln2490_fu_1864_p2 = (zext_ln2474_2_reg_3212 + shl_ln2467_2_reg_3154);

assign add_ln2491_1_fu_2179_p2 = (idx_reg_613 + fstride_cast_reg_3085);

assign add_ln2491_2_fu_2184_p2 = (zext_ln1323_3_reg_3146 + idx121_reg_625);

assign add_ln2497_1_fu_2353_p2 = (zext_ln1323_3_reg_3146 + idx123_reg_668);

assign add_ln2500_1_fu_2318_p2 = (shl_ln53_fu_2310_p3 + tmp);

assign add_ln2500_fu_2305_p2 = (zext_ln2500_fu_2301_p1 + add_ln2467_reg_3169);

assign add_ln2513_1_fu_2909_p2 = (idx133_fu_226 + Fstride_cast_reg_3095);

assign add_ln2513_2_fu_2914_p2 = (zext_ln1323_3_reg_3146 + idx131_fu_230);

assign add_ln685_10_fu_2097_p2 = (add_ln685_fu_2091_p2 + w_57_fu_2086_p2);

assign add_ln685_12_fu_2559_p2 = (vla18_q1 + sub_ln685_4_fu_2554_p2);

assign add_ln685_13_fu_2594_p2 = (zext_ln685_8_fu_2590_p1 + add_ln685_12_fu_2559_p2);

assign add_ln685_fu_2091_p2 = (w_55_fu_2052_p2 + zext_ln1521_fu_2082_p1);

assign add_ln697_fu_2636_p2 = (zext_ln697_1_fu_2632_p1 + sub_ln697_2_fu_2601_p2);

assign add_ln757_fu_1594_p2 = (zext_ln757_fu_1590_p1 + grp_modp_montymul_fu_800_ap_return);

assign add_ln967_fu_1757_p2 = (zext_ln967_fu_1753_p1 + tmp);

assign add_ln968_1_fu_1797_p2 = (zext_ln968_1_fu_1793_p1 + tmp);

assign add_ln968_fu_1780_p2 = (m_4_reg_3100 + zext_ln968_fu_1777_p1);

assign and_ln1525_fu_2073_p2 = (select_ln1525_fu_2065_p3 & p_reg_3251);

assign and_ln1544_fu_2213_p2 = (z_84_reg_497 & sext_ln1544_fu_2209_p1);

assign and_ln635_fu_1884_p2 = (select_ln635_fu_1876_p3 & p_reg_3251);

assign and_ln685_5_fu_2119_p2 = (select_ln685_7_fu_2111_p3 & p_reg_3251);

assign and_ln685_6_fu_2581_p2 = (select_ln685_8_fu_2573_p3 & p_reg_3251);

assign and_ln685_fu_1548_p2 = (select_ln685_fu_1540_p3 & p_reg_3251);

assign and_ln697_1_fu_2623_p2 = (select_ln697_2_fu_2615_p3 & p_reg_3251);

assign and_ln697_fu_2240_p2 = (select_ln697_fu_2232_p3 & p_reg_3251);

assign and_ln757_fu_1581_p2 = (select_ln757_fu_1573_p3 & p_reg_3251);

assign and_ln781_fu_1635_p2 = (x_assign_reg_3181 & trunc_ln779_fu_1620_p1);

assign and_ln813_fu_1708_p2 = (xor_ln813_fu_1686_p2 & select_ln813_fu_1700_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_phi_mux_g_assign_4_phi_fu_531_p4 = g_assign_4_reg_528;

assign ap_phi_mux_r_10_phi_fu_490_p4 = r_10_reg_487;

assign ap_phi_mux_z_63_phi_fu_552_p4 = reg_549;

assign dt_fu_2388_p2 = t_reg_688 << 64'd1;

assign e_fu_1663_p2 = ($signed(zext_ln1324_reg_3277) + $signed(32'd4294967294));

assign empty_fu_1214_p1 = logn[2:0];

assign fk_fu_1286_p2 = (zext_ln2466_fu_1282_p1 + tmp);

assign flen_cast14_fu_1194_p1 = flen_r;

assign fstride_cast_fu_1198_p1 = fstride_r;

assign grp_fu_3000_p1 = zext_ln1323_1_reg_3134;

assign grp_fu_3000_p2 = zext_ln2457_reg_3400;

assign grp_fu_3006_p1 = t_reg_688[12:0];

assign grp_fu_3006_p2 = zext_ln1323_1_reg_3134;

assign grp_fu_3006_p3 = zext_ln2457_reg_3400;

assign grp_modp_NTT2_ext_1_fu_1171_ap_start = grp_modp_NTT2_ext_1_fu_1171_ap_start_reg;

assign grp_zint_rebuild_CRT_1_fu_1154_ap_start = grp_zint_rebuild_CRT_1_fu_1154_ap_start_reg;

assign hm_fu_2374_p4 = {{m_reg_679[10:1]}};

assign i_11_fu_1629_p2 = (i_reg_476 + 32'd1);

assign i_12_fu_1680_p2 = ($signed(i_9_reg_538) + $signed(6'd63));

assign icmp_ln1339_fu_2368_p2 = ((tmp_178_fu_2358_p4 == 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln1345_fu_2398_p2 = ((u_193_reg_712 == hm_reg_3500) ? 1'b1 : 1'b0);

assign icmp_ln1354_fu_2462_p2 = ((v_31_reg_723 == t_reg_688) ? 1'b1 : 1'b0);

assign icmp_ln1373_fu_2643_p2 = ((k_10_reg_745 == m_4_reg_3100) ? 1'b1 : 1'b0);

assign icmp_ln1520_fu_2046_p2 = ((u_191_fu_2007_p2 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln2284_fu_2814_p2 = ((reg_791 < Flen) ? 1'b1 : 1'b0);

assign icmp_ln2293_fu_2824_p2 = ((v_fu_2819_p2 < zext_ln1323_reg_3128) ? 1'b1 : 1'b0);

assign icmp_ln2474_fu_1387_p2 = ((u_112_fu_222 == tlen_reg_3122) ? 1'b1 : 1'b0);

assign icmp_ln2485_fu_1817_p2 = ((v_021_reg_591 == m_4_reg_3100) ? 1'b1 : 1'b0);

assign icmp_ln2491_fu_1943_p2 = ((v_27_reg_602 == m_4_reg_3100) ? 1'b1 : 1'b0);

assign icmp_ln2497_fu_2264_p2 = ((v_28_reg_657 == m_4_reg_3100) ? 1'b1 : 1'b0);

assign icmp_ln2513_fu_2719_p2 = ((u_fu_234 == m_4_reg_3100) ? 1'b1 : 1'b0);

assign icmp_ln779_fu_1624_p2 = ((shl_ln779_fu_1614_p2 > x_assign_85_cast_reg_3186) ? 1'b1 : 1'b0);

assign icmp_ln781_fu_1640_p2 = ((and_ln781_fu_1635_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln954_fu_1651_p2 = ((k_7_reg_519 < 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln962_fu_1724_p2 = ((u_116_reg_580 == m_4_reg_3100) ? 1'b1 : 1'b0);

assign k_12_fu_1657_p2 = (k_7_reg_519 + 4'd1);

assign k_13_fu_2648_p2 = (k_10_reg_745 + 11'd1);

assign k_9_cast47_fu_1342_p1 = k_9_fu_1336_p2;

assign k_9_fu_1336_p2 = (3'd2 - empty_fu_1214_p1);

assign logn_cast4_fu_1210_p1 = logn;

assign logn_cast7_fu_1202_p1 = logn;

assign lshr_ln1544_2_fu_2155_p4 = {{add_ln1544_2_fu_2150_p2[14:2]}};

assign lshr_ln2281_1_fu_2757_p4 = {{add_ln2281_1_fu_2752_p2[14:2]}};

assign lshr_ln2487_1_fu_1925_p4 = {{add_ln2487_2_fu_1920_p2[14:2]}};

assign lshr_ln2500_1_fu_2338_p4 = {{x_fu_2292_p2[14:2]}};

assign lshr_ln49_fu_2888_p4 = {{add_ln2297_1_fu_2883_p2[14:2]}};

assign lshr_ln50_fu_1762_p4 = {{add_ln967_fu_1757_p2[14:2]}};

assign lshr_ln51_fu_1802_p4 = {{add_ln968_1_fu_1797_p2[14:2]}};

assign lshr_ln52_fu_1849_p4 = {{add_ln2487_fu_1844_p2[14:2]}};

assign lshr_ln53_fu_2031_p4 = {{add_ln1524_2_fu_2026_p2[14:2]}};

assign lshr_ln54_fu_2323_p4 = {{add_ln2500_1_fu_2318_p2[14:2]}};

assign lshr_ln56_fu_2676_p4 = {{r_13_fu_2671_p2[14:2]}};

assign lshr_ln57_fu_2447_p4 = {{add_ln1351_2_fu_2442_p2[14:2]}};

assign lshr_ln58_fu_2514_p4 = {{r1_fu_2491_p2[14:2]}};

assign lshr_ln59_fu_2529_p4 = {{r2_fu_2509_p2[14:2]}};

assign lshr_ln813_fu_1692_p2 = e_reg_3335 >> sext_ln808_reg_3340;

assign lshr_ln_fu_2851_p4 = {{add_ln2293_1_fu_2846_p2[14:2]}};

assign m_4_fu_1226_p2 = 11'd1 << zext_ln2462_1_fu_1222_p1;

assign mul_ln656_fu_1431_p0 = sext_ln1324_fu_1417_p1;

assign mul_ln656_fu_1431_p1 = zext_ln656_fu_1427_p1;

assign mul_ln657_fu_1449_p0 = sext_ln1324_fu_1417_p1;

assign mul_ln658_fu_1471_p0 = sext_ln1324_reg_3264;

assign mul_ln659_fu_1486_p0 = sext_ln1324_reg_3264;

assign ni_fu_1356_p2 = 26'd1 << sub_i92_cast_fu_1352_p1;

assign p0i_fu_1503_p0 = (31'd2 - mul_ln659_fu_1486_p2);

assign p0i_fu_1503_p1 = ($signed(31'd0) - $signed(y_57_fu_1481_p2));

assign r1_fu_2491_p2 = (shl_ln57_fu_2483_p3 + tmp);

assign r2_fu_2509_p2 = (shl_ln1348_1_fu_2501_p3 + tmp);

assign r_13_fu_2671_p2 = (shl_ln55_fu_2663_p3 + tmp);

assign scl_cast_fu_1190_p0 = scl;

assign scl_cast_fu_1190_p1 = scl_cast_fu_1190_p0;

assign select_ln1525_fu_2065_p3 = ((tmp_175_fu_2057_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln635_fu_1876_p3 = ((tmp_174_fu_1868_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln685_7_fu_2111_p3 = ((tmp_176_fu_2103_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln685_8_fu_2573_p3 = ((tmp_179_fu_2565_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln685_fu_1540_p3 = ((tmp_171_fu_1532_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln697_2_fu_2615_p3 = ((tmp_180_fu_2607_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln697_fu_2232_p3 = ((tmp_177_fu_2224_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln757_fu_1573_p3 = ((trunc_ln735_fu_1569_p1[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln813_fu_1700_p3 = ((trunc_ln813_fu_1696_p1[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign sext_ln1324_fu_1417_p0 = PRIMES_p_q0;

assign sext_ln1324_fu_1417_p1 = sext_ln1324_fu_1417_p0;

assign sext_ln1510_fu_2003_p1 = phi_ln1510_reg_637;

assign sext_ln1521_fu_2078_p1 = $signed(and_ln1525_fu_2073_p2);

assign sext_ln1544_fu_2209_p1 = $signed(sub_ln1544_fu_2203_p2);

assign sext_ln2281_fu_2802_p1 = $signed(ysign_fu_2792_p4);

assign sext_ln635_fu_1889_p1 = $signed(and_ln635_fu_1884_p2);

assign sext_ln685_5_fu_2124_p1 = $signed(and_ln685_5_fu_2119_p2);

assign sext_ln685_6_fu_2586_p1 = $signed(and_ln685_6_fu_2581_p2);

assign sext_ln685_fu_1553_p1 = $signed(and_ln685_fu_1548_p2);

assign sext_ln697_1_fu_2628_p1 = $signed(and_ln697_1_fu_2623_p2);

assign sext_ln697_fu_2245_p1 = $signed(and_ln697_fu_2240_p2);

assign sext_ln757_fu_1586_p1 = $signed(and_ln757_fu_1581_p2);

assign sext_ln808_fu_1668_p1 = i_9_reg_538;

assign shl_ln1348_1_fu_2501_p3 = {{add_ln1348_2_fu_2496_p2}, {2'd0}};

assign shl_ln2294_fu_2939_p2 = wy_fu_2933_p3 << scl_cast_reg_3075;

assign shl_ln2457_1_fu_2284_p3 = {{add_ln2457_2_fu_2279_p2}, {2'd0}};

assign shl_ln2467_1_fu_1312_p3 = {{add_ln2467_fu_1306_p2}, {2'd0}};

assign shl_ln2467_2_fu_1266_p3 = {{m_4_fu_1226_p2}, {1'd0}};

assign shl_ln2467_fu_1292_p2 = zext_ln1323_4_fu_1262_p1 << zext_ln2462_fu_1218_p1;

assign shl_ln2487_1_fu_1912_p3 = {{add_ln2487_1_fu_1907_p2}, {2'd0}};

assign shl_ln44_fu_2744_p3 = {{add_ln2281_2_fu_2739_p2}, {2'd0}};

assign shl_ln45_fu_2838_p3 = {{add_ln2293_fu_2833_p2}, {2'd0}};

assign shl_ln46_fu_2875_p3 = {{add_ln2297_fu_2870_p2}, {2'd0}};

assign shl_ln47_fu_1745_p3 = {{REV10_q0}, {2'd0}};

assign shl_ln48_fu_1785_p3 = {{add_ln968_fu_1780_p2}, {2'd0}};

assign shl_ln49_fu_1832_p3 = {{trunc_ln2487_fu_1828_p1}, {2'd0}};

assign shl_ln50_fu_1986_p3 = {{add_ln2490_reg_3394}, {2'd0}};

assign shl_ln51_fu_1963_p3 = {{add_ln2457_fu_1958_p2}, {2'd0}};

assign shl_ln52_fu_2018_p3 = {{add_ln1524_3_fu_2013_p2}, {2'd0}};

assign shl_ln53_fu_2310_p3 = {{add_ln2500_fu_2305_p2}, {2'd0}};

assign shl_ln54_fu_2142_p3 = {{add_ln1544_fu_2138_p2}, {2'd0}};

assign shl_ln55_fu_2663_p3 = {{add_ln1329_fu_2658_p2}, {2'd0}};

assign shl_ln56_fu_2431_p3 = {{add_ln1351_1_reg_3529}, {2'd0}};

assign shl_ln57_fu_2483_p3 = {{add_ln1348_fu_2478_p2}, {2'd0}};

assign shl_ln685_fu_1520_p2 = z_83_fu_1514_p2 << 32'd1;

assign shl_ln779_fu_1614_p2 = 32'd1 << i_reg_476;

assign shl_ln966_fu_1735_p2 = trunc_ln962_fu_1720_p1 << k_9_cast47_reg_3191;

assign shl_ln_fu_1274_p3 = {{m_4_fu_1226_p2}, {3'd0}};

assign sub9_i_fu_2707_p1 = scl;

assign sub9_i_fu_2707_p2 = ($signed(6'd31) - $signed(sub9_i_fu_2707_p1));

assign sub_i92_cast_fu_1352_p1 = sub_i92_fu_1346_p2;

assign sub_i92_fu_1346_p2 = (logn_cast4_fu_1210_p1 ^ 5'd31);

assign sub_ln1544_fu_2203_p2 = (3'd0 - zext_ln1544_3_fu_2199_p1);

assign sub_ln2281_fu_2786_p2 = (3'd0 - zext_ln2281_1_fu_2782_p1);

assign sub_ln2297_fu_2967_p2 = (vla18_q0 - zext_ln2287_fu_2954_p1);

assign sub_ln685_4_fu_2554_p2 = (vla18_q0 - zext_ln1324_reg_3277);

assign sub_ln685_fu_1526_p2 = (shl_ln685_fu_1520_p2 - zext_ln1324_fu_1467_p1);

assign sub_ln697_2_fu_2601_p2 = (vla18_q0 - vla18_q1);

assign sub_ln697_fu_2219_p2 = (x_26_reg_3447 - and_ln1544_fu_2213_p2);

assign t1_fu_1320_p2 = (shl_ln2467_1_fu_1312_p3 + tmp);

assign tlen_fu_1240_p2 = (flen_r + 8'd1);

assign tmp_171_fu_1532_p3 = sub_ln685_fu_1526_p2[32'd31];

assign tmp_173_fu_1672_p3 = i_9_reg_538[32'd5];

assign tmp_174_fu_1868_p3 = vla18_q0[32'd31];

assign tmp_175_fu_2057_p3 = w_55_fu_2052_p2[32'd31];

assign tmp_176_fu_2103_p3 = add_ln685_10_fu_2097_p2[32'd31];

assign tmp_177_fu_2224_p3 = sub_ln697_fu_2219_p2[32'd31];

assign tmp_178_fu_2358_p4 = {{m_reg_679[10:1]}};

assign tmp_179_fu_2565_p3 = add_ln685_12_fu_2559_p2[32'd31];

assign tmp_180_fu_2607_p3 = sub_ln697_2_fu_2601_p2[32'd31];

assign trunc_ln1324_fu_1413_p0 = PRIMES_p_q0;

assign trunc_ln1324_fu_1413_p1 = trunc_ln1324_fu_1413_p0[23:0];

assign trunc_ln1329_fu_2654_p1 = idx125_reg_756[12:0];

assign trunc_ln1345_fu_2423_p1 = reg_700[12:0];

assign trunc_ln1348_fu_2474_p1 = idx127_reg_734[12:0];

assign trunc_ln2287_fu_2983_p1 = w_fu_2977_p2[30:0];

assign trunc_ln2293_fu_2829_p1 = v_fu_2819_p2[12:0];

assign trunc_ln2294_fu_2944_p1 = shl_ln2294_fu_2939_p2[30:0];

assign trunc_ln2297_1_fu_2963_p1 = tw_1_fu_2958_p2[30:0];

assign trunc_ln2297_2_fu_2866_p1 = reg_791[12:0];

assign trunc_ln2297_fu_2810_p1 = idx133_fu_226[12:0];

assign trunc_ln2457_1_fu_1954_p1 = idx121_reg_625[12:0];

assign trunc_ln2457_2_fu_2275_p1 = idx123_reg_668[12:0];

assign trunc_ln2457_fu_2730_p1 = idx131_fu_230[12:0];

assign trunc_ln2467_fu_1298_p1 = shl_ln2467_fu_1292_p2[12:0];

assign trunc_ln2487_fu_1828_p1 = v_021_reg_591[9:0];

assign trunc_ln2491_fu_1976_p1 = idx_reg_613[12:0];

assign trunc_ln2500_fu_2297_p1 = v_28_reg_657[9:0];

assign trunc_ln735_fu_1569_p1 = grp_modp_montymul_fu_800_ap_return[0:0];

assign trunc_ln779_fu_1620_p1 = shl_ln779_fu_1614_p2[7:0];

assign trunc_ln813_fu_1696_p1 = lshr_ln813_fu_1692_p2[0:0];

assign trunc_ln962_fu_1720_p1 = u_116_reg_580[9:0];

assign trunc_ln9_fu_2189_p4 = {{vla18_q0[31:30]}};

assign trunc_ln_fu_2772_p4 = {{vla18_q1[31:30]}};

assign tw_1_fu_2958_p2 = wy_fu_2933_p3 >> zext_ln2513_reg_3614;

assign u_112_cast_cast_cast_cast_fu_2703_p1 = $unsigned(u_112_cast_cast_cast_fu_2700_p1);

assign u_112_cast_cast_cast_fu_2700_p1 = $signed(sch);

assign u_188_fu_2903_p2 = (reg_791 + 64'd1);

assign u_189_fu_2724_p2 = (u_fu_234 + 11'd1);

assign u_190_fu_1729_p2 = (u_116_reg_580 + 11'd1);

assign u_191_fu_2007_p2 = ($signed(phi_ln1510_reg_637) + $signed(9'd511));

assign u_192_fu_1392_p2 = (u_112_fu_222 + 8'd1);

assign u_194_fu_2403_p2 = (u_193_reg_712 + 10'd1);

assign v1_1_fu_2549_p2 = (dt_reg_3510 + reg_700);

assign v_26_fu_1822_p2 = (v_021_reg_591 + 11'd1);

assign v_29_fu_2269_p2 = (v_28_reg_657 + 11'd1);

assign v_30_fu_1948_p2 = (v_27_reg_602 + 11'd1);

assign v_32_fu_2468_p2 = (v_31_reg_723 + 64'd1);

assign v_fu_2819_p2 = (reg_791 - u_112_cast_cast_cast_cast_reg_3608);

assign w_54_fu_1897_p2 = (vla18_q0 + zext_ln635_fu_1893_p1);

assign w_55_fu_2052_p2 = (vla18_q0 - zext_ln1324_reg_3277);

assign w_57_fu_2086_p2 = (grp_modp_montymul_fu_800_ap_return - zext_ln1324_reg_3277);

assign w_fu_2977_p2 = (sub_ln2297_fu_2967_p2 - zext_ln2284_fu_2973_p1);

assign wy_fu_2933_p3 = ((icmp_ln2293_reg_3650[0:0] == 1'b1) ? vla18_q1 : zext_ln2281_2_reg_3637);

assign wys_fu_2948_p1 = reg_779;

assign wys_fu_2948_p2 = (wys_fu_2948_p1 | trunc_ln2294_fu_2944_p1);

assign x_19_fu_1997_p2 = (zext_ln2490_fu_1993_p1 + tmp);

assign x_22_fu_1971_p2 = (shl_ln51_fu_1963_p3 + tmp);

assign x_26_fu_2132_p2 = (zext_ln685_7_fu_2128_p1 + add_ln685_10_fu_2097_p2);

assign x_assign_85_cast_fu_1332_p1 = x_assign_fu_1326_p2;

assign x_assign_fu_1326_p2 = ($signed(flen_r) + $signed(8'd255));

assign x_fu_2292_p2 = (shl_ln2457_1_fu_2284_p3 + tmp);

assign xor_ln813_fu_1686_p1 = reg_700;

assign xor_ln813_fu_1686_p2 = (xor_ln813_fu_1686_p1 ^ grp_modp_montymul_fu_800_ap_return);

assign y_54_fu_1421_p2 = (24'd2 - trunc_ln1324_fu_1413_p1);

assign y_55_fu_1443_p0 = (31'd2 - mul_ln656_fu_1431_p2);

assign y_55_fu_1443_p1 = zext_ln656_fu_1427_p1;

assign y_56_fu_1461_p0 = (31'd2 - mul_ln657_fu_1449_p2);

assign y_57_fu_1481_p0 = (31'd2 - mul_ln658_fu_1471_p2);

assign ysign_fu_2792_p4 = {{sub_ln2281_fu_2786_p2[2:1]}};

assign z_80_fu_1714_p1 = reg_700;

assign z_80_fu_1714_p2 = (z_80_fu_1714_p1 ^ and_ln813_fu_1708_p2);

assign z_82_fu_2253_p2 = (zext_ln697_fu_2249_p1 + sub_ln697_fu_2219_p2);

assign z_83_fu_1514_p2 = ($signed(32'd2147483648) - $signed(zext_ln1324_fu_1467_p1));

assign z_fu_1561_p2 = (zext_ln685_fu_1557_p1 + sub_ln685_fu_1526_p2);

assign zext_ln1323_1_fu_1250_p1 = tlen_fu_1240_p2;

assign zext_ln1323_2_fu_1254_p1 = tlen_fu_1240_p2;

assign zext_ln1323_3_fu_1258_p1 = tlen_fu_1240_p2;

assign zext_ln1323_4_fu_1262_p1 = tlen_fu_1240_p2;

assign zext_ln1323_fu_1246_p1 = tlen_fu_1240_p2;

assign zext_ln1324_1_fu_1509_p1 = p0i_fu_1503_p2;

assign zext_ln1324_fu_1467_p1 = $unsigned(sext_ln1324_reg_3264);

assign zext_ln1329_1_fu_1236_p1 = m_4_fu_1226_p2;

assign zext_ln1329_fu_1232_p1 = m_4_fu_1226_p2;

assign zext_ln1330_fu_1362_p1 = ni_fu_1356_p2;

assign zext_ln1343_fu_2384_p1 = hm_fu_2374_p4;

assign zext_ln1345_fu_2394_p1 = hm_fu_2374_p4;

assign zext_ln1351_1_fu_2438_p1 = shl_ln56_fu_2431_p3;

assign zext_ln1351_2_fu_2457_p1 = lshr_ln57_fu_2447_p4;

assign zext_ln1351_fu_2409_p1 = u_193_reg_712;

assign zext_ln1358_fu_2524_p1 = lshr_ln58_fu_2514_p4;

assign zext_ln1359_fu_2539_p1 = lshr_ln59_fu_2529_p4;

assign zext_ln1374_fu_2686_p1 = lshr_ln56_fu_2676_p4;

assign zext_ln1521_fu_2082_p1 = $unsigned(sext_ln1521_fu_2078_p1);

assign zext_ln1524_fu_2041_p1 = lshr_ln53_fu_2031_p4;

assign zext_ln1544_3_fu_2199_p1 = trunc_ln9_fu_2189_p4;

assign zext_ln1544_fu_2165_p1 = lshr_ln1544_2_fu_2155_p4;

assign zext_ln2281_1_fu_2782_p1 = trunc_ln_fu_2772_p4;

assign zext_ln2281_2_fu_2806_p1 = $unsigned(sext_ln2281_fu_2802_p1);

assign zext_ln2281_fu_2767_p1 = lshr_ln2281_1_fu_2757_p4;

assign zext_ln2284_fu_2973_p1 = cc_reg_767;

assign zext_ln2287_fu_2954_p1 = wys_fu_2948_p2;

assign zext_ln2293_fu_2861_p1 = lshr_ln_fu_2851_p4;

assign zext_ln2297_fu_2898_p1 = lshr_ln49_fu_2888_p4;

assign zext_ln2298_fu_2987_p1 = trunc_ln2287_fu_2983_p1;

assign zext_ln2457_fu_1940_p1 = add_ln2490_reg_3394;

assign zext_ln2462_1_fu_1222_p1 = logn;

assign zext_ln2462_fu_1218_p1 = logn;

assign zext_ln2466_fu_1282_p1 = shl_ln_fu_1274_p3;

assign zext_ln2467_fu_1302_p1 = shl_ln2467_2_fu_1266_p3;

assign zext_ln2474_1_fu_1378_p1 = u_112_fu_222;

assign zext_ln2474_2_fu_1383_p1 = u_112_fu_222;

assign zext_ln2474_fu_1366_p1 = flen_r;

assign zext_ln2487_1_fu_1859_p1 = lshr_ln52_fu_1849_p4;

assign zext_ln2487_2_fu_1904_p1 = trunc_ln2487_reg_3384;

assign zext_ln2487_3_fu_1935_p1 = lshr_ln2487_1_fu_1925_p4;

assign zext_ln2487_fu_1840_p1 = shl_ln49_fu_1832_p3;

assign zext_ln2490_fu_1993_p1 = shl_ln50_fu_1986_p3;

assign zext_ln2494_fu_2260_p1 = lshr_ln55_reg_3458;

assign zext_ln2500_1_fu_2333_p1 = lshr_ln54_fu_2323_p4;

assign zext_ln2500_2_fu_2348_p1 = lshr_ln2500_1_fu_2338_p4;

assign zext_ln2500_fu_2301_p1 = trunc_ln2500_fu_2297_p1;

assign zext_ln2513_fu_2712_p1 = sub9_i_fu_2707_p2;

assign zext_ln635_fu_1893_p1 = $unsigned(sext_ln635_fu_1889_p1);

assign zext_ln656_fu_1427_p1 = y_54_fu_1421_p2;

assign zext_ln685_7_fu_2128_p1 = $unsigned(sext_ln685_5_fu_2124_p1);

assign zext_ln685_8_fu_2590_p1 = $unsigned(sext_ln685_6_fu_2586_p1);

assign zext_ln685_fu_1557_p1 = $unsigned(sext_ln685_fu_1553_p1);

assign zext_ln697_1_fu_2632_p1 = $unsigned(sext_ln697_1_fu_2628_p1);

assign zext_ln697_fu_2249_p1 = $unsigned(sext_ln697_fu_2245_p1);

assign zext_ln757_9_fu_1610_p1 = R2_fu_1600_p4;

assign zext_ln757_fu_1590_p1 = $unsigned(sext_ln757_fu_1586_p1);

assign zext_ln937_fu_1646_p1 = PRIMES_g_q0;

assign zext_ln966_fu_1740_p1 = shl_ln966_fu_1735_p2;

assign zext_ln967_1_fu_1772_p1 = lshr_ln50_fu_1762_p4;

assign zext_ln967_fu_1753_p1 = shl_ln47_fu_1745_p3;

assign zext_ln968_1_fu_1793_p1 = shl_ln48_fu_1785_p3;

assign zext_ln968_2_fu_1812_p1 = lshr_ln51_fu_1802_p4;

assign zext_ln968_fu_1777_p1 = v_25_reg_3371;

always @ (posedge ap_clk) begin
    flen_cast14_reg_3080[8] <= 1'b0;
    fstride_cast_reg_3085[17:8] <= 10'b0000000000;
    logn_cast7_reg_3090[31:4] <= 28'b0000000000000000000000000000;
    Fstride_cast_reg_3095[18:9] <= 10'b0000000000;
    zext_ln1329_reg_3112[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln1329_1_reg_3117[11] <= 1'b0;
    zext_ln1323_reg_3128[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln1323_1_reg_3134[12:8] <= 5'b00000;
    zext_ln1323_2_reg_3140[8] <= 1'b0;
    zext_ln1323_3_reg_3146[17:8] <= 10'b0000000000;
    shl_ln2467_2_reg_3154[0] <= 1'b0;
    zext_ln2467_reg_3164[0] <= 1'b0;
    zext_ln2467_reg_3164[12] <= 1'b0;
    x_assign_85_cast_reg_3186[31:8] <= 24'b000000000000000000000000;
    k_9_cast47_reg_3191[9:3] <= 7'b0000000;
    zext_ln1330_reg_3196[31:26] <= 6'b000000;
    zext_ln2474_reg_3201[12:8] <= 5'b00000;
    zext_ln2474_1_reg_3207[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln2474_2_reg_3212[11:8] <= 4'b0000;
    zext_ln1324_reg_3277[31] <= 1'b0;
    zext_ln1324_1_reg_3291[31] <= 1'b0;
    zext_ln757_9_reg_3304[31] <= 1'b0;
    zext_ln2457_reg_3400[12] <= 1'b0;
    zext_ln1343_reg_3505[10] <= 1'b0;
    dt_reg_3510[0] <= 1'b0;
    zext_ln1345_reg_3516[11:10] <= 2'b00;
    u_112_cast_cast_cast_cast_reg_3608[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln2513_reg_3614[31:6] <= 26'b00000000000000000000000000;
    zext_ln2281_2_reg_3637[31] <= 1'b0;
end

endmodule //keygen_poly_sub_scaled_ntt_1
